# 1/29/18 SNP calling notes

*Raw tar files returned from GSL were extracted and names of folders were changed to correspond to a single pool (lane) run for each batch.  The .fastq.gz files for each library were QC'ed with fastqc and then adapters/contamination was removed using bbduk.  The filtered and trimmed reads are located at:

```linux
/media/disk6/ARF/RNASEQ/trimmedfiltreads
```

*The above path is the starting directory for processing SNPs.  Notes of lane extraction, fastqc, and filter/trim processing are on git at:

```linux
Breeding-Value-Prediction/disk6directory/RNASEQ/rawreads/processingnotes
```

*Below is a list of all steps. First each step will be practiced and once a final method for each step is determined a pipe command will be built for as many steps as possible.

## 1. Align .fastq.gz techincal reps to 86K transcriptome with bowtie

*Build bowtie2 index:

```linux
cd /media/disk6/ARF/RNASEQ
./software/bowtie/bowtie2-build -f ./references/Pita.86ktxptome.fasta Pita.86k
```

*Practice run bowtie2:

```linux
./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane01/96_S12_L001_R1_001.fastq.gz -S out.sam
```
*The above outputs a .sam file that is uncompressed

*The below puts out a .bam file that is compressed. Note that when using samtools view "q" can be used to filter low quality reads. Should this be used?

```linux
while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane01/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane01/$file; done < ./rawreads/EWfasta/lane01/lane01.list;while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane02/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane02/$file; done < ./rawreads/EWfasta/lane02/lane02.list;

while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane03/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane03/$file; done < ./rawreads/EWfasta/lane03/lane03.list; while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane04/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane04/$file; done < ./rawreads/EWfasta/lane04/lane04.list; while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane05/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane05/$file; done < ./rawreads/EWfasta/lane05/lane05.list; while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane06/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane06/$file; done < ./rawreads/EWfasta/lane06/lane06.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane07/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane07/$file; done < ./rawreads/EWfasta/lane07/lane07.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane08/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane08/$file; done < ./rawreads/EWfasta/lane08/lane08.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane09/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane09/$file; done < ./rawreads/EWfasta/lane09/lane09.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane10/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane10/$file; done < ./rawreads/EWfasta/lane10/lane10.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane11/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane11/$file; done < ./rawreads/EWfasta/lane11/lane11.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/EW/lane12/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/EW/lane12/$file; done < ./rawreads/EWfasta/lane12/lane12.list;while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane01/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane01/$file; done < ./rawreads/LGEPfasta/lane01/lane01.list;while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane02/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane02/$file; done < ./rawreads/LGEPfasta/lane02/lane02.list;while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane03/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane03/$file; done < ./rawreads/LGEPfasta/lane03/lane03.list; while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane04/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane04/$file; done < ./rawreads/LGEPfasta/lane04/lane04.list; while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane05/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane05/$file; done < ./rawreads/LGEPfasta/lane05/lane05.list; while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane06/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane06/$file; done < ./rawreads/LGEPfasta/lane06/lane06.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane07/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane07/$file; done < ./rawreads/LGEPfasta/lane07/lane07.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane08/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane08/$file; done < ./rawreads/LGEPfasta/lane08/lane08.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane09/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane09/$file; done < ./rawreads/LGEPfasta/lane09/lane09.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane10/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane10/$file; done < ./rawreads/LGEPfasta/lane10/lane10.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane11/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane11/$file; done < ./rawreads/LGEPfasta/lane11/lane11.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane12/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane12/$file; done < ./rawreads/LGEPfasta/lane12/lane12.list; 



while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane13/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane13/$file; done < ./rawreads/LGEPfasta/lane13/lane13.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane14/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane14/$file; done < ./rawreads/LGEPfasta/lane14/lane14.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane15/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane15/$file; done < ./rawreads/LGEPfasta/lane15/lane15.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane16/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane16/$file; done < ./rawreads/LGEPfasta/lane16/lane16.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane17/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane17/$file; done < ./rawreads/LGEPfasta/lane17/lane17.list;  while read file; do ./software/bowtie/bowtie2 -p 60 -x ./references/Pta.86k -U ./trimmedfiltreads/LGEP/lane18/$file | ./software/samtools-1.6/samtools view -@ 60 -b1 - -o ./snps/86k/LGEP/lane18/$file; done < ./rawreads/LGEPfasta/lane18/lane18.list; 

```

## 2. Convert sam file to bam
## 3. Merge technical rep bam files
## 4. Sort biological rep bam file
## 5. Mark/remove duplicates within bam files
## 6. Add RG & SM to each biological rep
## 7. Provide list of bams to freebayes and call SNPs
## 8. Filter VCF for no missing SNPs
